sudo: false
language: node_js
node_js:
  - stable

before_install:
  - gem update --system
  - gem install sass
  - npm update -g npm
  - npm install -g bower grunt-cli jspm
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-grunt-symfony' ]; then cd .. && eval "mv $currentfolder generator-grunt-symfony" && cd generator-grunt-symfony; fi

matrix:
  fast_finish: true
